## Event Collection Methods
# Note: Only enable one - webapi OR mqtt
frigate:
  # Frigate host URL (ex. https://frigate.yourdomain.local)
  # This is required for both collection methods
  server: 
  # Set to true if using SSL & a self-signed certificate
  ignoressl: false

  webapi:
    # Set to true to enable event collection via the web API
    enabled: 
    # Interval between checking for new events, in seconds
    interval: 
    
  mqtt: 
    # Set to true to enable event collection via MQTT
    enabled: 
    # MQTT host IP
    server: 
    # MQTT host port. Default is 1883 if this is not set
    port:
    # MQTT Authentication. Leave both blank for anonymous
    username: 
    password: 
  
  cameras:
    # List of cameras to exclude from being monitored
    # Camera names must match frigate configuration
    exclude:
      - test_cam_01


## Alerting methods
# Any combination of alert destinations can be configured
alerts:  
  # General config applies to all alert methods below
  general:
    # Title for any alert messages (Default: Frigate Alert)
    title:

  discord:
    # Set to true to enable alerting via Discord messages
    enabled: false
    # Insert full webhook URL below
    webhook: 
  
  gotify:
    # Set to true to enable alerting via a Gotify push notification server
    enabled: false
    # Server URL (ex. https://push.yourdomain.local)
    server:
    # Application token generated by Gotify
    token: 
    # Set to true if using SSL & a self-signed certificate
    ignoressl:
  
  smtp:
    # Set to true to enable alerting via SMTP
    enabled: false
    # SMTP server host (ex. smtp.gmail.com)
    server: 
    # SMTP port
    port: 
    # Sending address / username
    user:
    # SMTP password for above user
    password:
    # Email alerts sent to any addresses listed below, separated by comma
    recipient:


## App Monitoring
# Sends HTTP GET to provided URL for aliveness checks
monitor:
  # Set to true to enable app monitoring
  enabled: false
  # URL for monitoring server
  url: 
  # Interval between monitoring check-in events, in seconds
  interval: 
  # Set to true if using SSL & a self-signed certificate
  ignoressl: 